# Generated by Django 4.2.30 on 2026-05-27 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0003_rulecondition_channel_rulecondition_dataset_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rulecondition',
            name='aggregate_fn',
            field=models.CharField(blank=True, choices=[('avg', 'Average'), ('min', 'Minimum'), ('max', 'Maximum')], help_text='Rolling aggregate function (windowed_aggregate type only).', max_length=10),
        ),
        migrations.AddField(
            model_name='rulecondition',
            name='window_minutes',
            field=models.PositiveIntegerField(blank=True, help_text='Window length in minutes (windowed_aggregate type only).', null=True),
        ),
        migrations.AlterField(
            model_name='rulecondition',
            name='condition_type',
            field=models.CharField(choices=[('stream', 'Stream value comparison'), ('staleness', 'Stream staleness'), ('feed_channel', 'Feed channel value comparison'), ('reference_value', 'Reference dataset value comparison'), ('windowed_aggregate', 'Windowed aggregate (avg/min/max over N minutes)')], max_length=20),
        ),
    ]
