# Generated by Django 4.2.30 on 2026-05-20 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_sprint20'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationEventType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(help_text='Stable event identifier, e.g. "device_offline". Stored on Notification.event_type.', max_length=64, unique=True)),
                ('label', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('critical', 'Critical')], default='info', max_length=10)),
                ('audience', models.CharField(choices=[('platform_admin', 'That Place Admins'), ('tenant', 'Tenant Admins')], help_text='platform_admin → delivered to all That Place Admins; tenant → delivered to the Tenant Admins of the emitting tenant.', max_length=20)),
                ('default_channels', models.JSONField(default=list, help_text='Channels this event delivers on, e.g. ["in_app", "email"].')),
                ('metadata_schema', models.JSONField(default=list, help_text='The event_data keys this event carries — documents the template placeholders available to message_template.')),
                ('message_template', models.TextField(help_text='Notification text. Placeholders are filled from event_data, e.g. "Device {device_name} went offline".')),
                ('is_active', models.BooleanField(default=True, help_text='Inactive event types are skipped by emit_event().')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['key'],
            },
        ),
        migrations.AddField(
            model_name='notification',
            name='message',
            field=models.TextField(blank=True, help_text='Rendered notification text. Populated for system/platform events from the NotificationEventType template; blank for alert notifications (the frontend renders those from the alert).'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='event_data',
            field=models.JSONField(blank=True, help_text='Context for the event — device name, serial, etc.', null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='event_type',
            field=models.CharField(blank=True, help_text='For system_event notifications: the NotificationEventType.key this notification was emitted from (e.g. device_offline).', max_length=64),
        ),
        migrations.AlterField(
            model_name='usernotificationpreference',
            name='phone_number',
            field=models.CharField(blank=True, help_text='E.164 format preferred (e.g. +61412345678). Required for SMS delivery.', max_length=20),
        ),
    ]
