# Generated by Django 4.2.30 on 2026-05-27 12:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rules', '0003_rulecondition_channel_rulecondition_dataset_and_more'),
        ('notifications', '0004_userpushtoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='RuleNotificationOptOut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('in_app', 'In-app'), ('email', 'Email'), ('sms', 'SMS'), ('push', 'Push')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_opt_outs', to='rules.rule')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rule_notification_opt_outs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'rule', 'channel')},
            },
        ),
    ]
