"""PKI utilities for MQTT device certificate issuance.

Issues per-device X.509 client certificates signed by the That Place CA.
The CA key and certificate are loaded from Django settings (environment
variables MQTT_CA_KEY_B64 / MQTT_CA_CERT_B64). In development, these are
auto-generated by the Mosquitto entrypoint script and printed to stdout
for copying into .env.

The issued certificate's CN is set to `scout-{serial_number}`. Mosquitto's
`use_subject_as_username true` on port 8883 extracts this CN as the MQTT
client username, which the Dynamic Security plugin uses for ACL lookups.

Ref: security_risks.md § SR-01
"""
import base64
import datetime
import logging

from cryptography import x509
from cryptography.hazmat.primitives import hashes, serialization
from cryptography.hazmat.primitives.asymmetric import rsa
from cryptography.x509.oid import NameOID
from django.conf import settings

logger = logging.getLogger(__name__)

_CERT_VALID_DAYS = 730  # 2 years per device certificate


def _load_ca() -> tuple:
    """Load CA key and certificate from Django settings.

    Returns (ca_key, ca_cert) as cryptography objects.
    Raises ValueError if the settings are missing or malformed.
    """
    ca_key_b64 = getattr(settings, 'MQTT_CA_KEY_B64', '')
    ca_cert_b64 = getattr(settings, 'MQTT_CA_CERT_B64', '')

    if not ca_key_b64 or not ca_cert_b64:
        raise ValueError(
            'MQTT_CA_KEY_B64 and MQTT_CA_CERT_B64 must be set to issue '
            'device certificates. In dev, copy the base64 values printed '
            'by the Mosquitto container on first start.'
        )

    ca_key = serialization.load_pem_private_key(
        base64.b64decode(ca_key_b64), password=None
    )
    ca_cert = x509.load_pem_x509_certificate(
        base64.b64decode(ca_cert_b64)
    )
    return ca_key, ca_cert


def issue_device_certificate(serial_number: str) -> dict:
    """Generate a key pair and issue a signed client certificate for a Scout.

    Generates a fresh 2048-bit RSA key pair. The private key never leaves
    this function — the caller is responsible for storing it encrypted and
    delivering it securely to the device operator.

    Certificate attributes:
      CN  = scout-{serial_number}  (used as MQTT username via use_subject_as_username)
      O   = That Place
      Key usage: digitalSignature, keyEncipherment
      Extended key usage: clientAuth

    Returns a dict:
      'cn'              (str)  Common Name — matches dynamic security client username
      'certificate_pem' (str)  PEM-encoded signed certificate (public, safe to store)
      'private_key_pem' (str)  PEM-encoded private key  *** KEEP SECURE ***
      'ca_cert_pem'     (str)  PEM-encoded CA certificate (needed by Scout for TLS)

    Raises ValueError if CA settings are missing.
    """
    ca_key, ca_cert = _load_ca()

    cn = f'scout-{serial_number}'

    device_key = rsa.generate_private_key(
        public_exponent=65537,
        key_size=2048,
    )

    now = datetime.datetime.now(datetime.timezone.utc)

    cert = (
        x509.CertificateBuilder()
        .subject_name(x509.Name([
            x509.NameAttribute(NameOID.COMMON_NAME, cn),
            x509.NameAttribute(NameOID.ORGANIZATION_NAME, 'That Place'),
        ]))
        .issuer_name(ca_cert.subject)
        .public_key(device_key.public_key())
        .serial_number(x509.random_serial_number())
        .not_valid_before(now)
        .not_valid_after(now + datetime.timedelta(days=_CERT_VALID_DAYS))
        .add_extension(
            x509.BasicConstraints(ca=False, path_length=None),
            critical=True,
        )
        .add_extension(
            x509.KeyUsage(
                digital_signature=True,
                key_encipherment=True,
                content_commitment=False,
                data_encipherment=False,
                key_agreement=False,
                key_cert_sign=False,
                crl_sign=False,
                encipher_only=False,
                decipher_only=False,
            ),
            critical=True,
        )
        .add_extension(
            x509.ExtendedKeyUsage([x509.ExtendedKeyUsageOID.CLIENT_AUTH]),
            critical=False,
        )
        .sign(ca_key, hashes.SHA256())
    )

    private_key_pem = device_key.private_bytes(
        encoding=serialization.Encoding.PEM,
        format=serialization.PrivateFormat.TraditionalOpenSSL,
        encryption_algorithm=serialization.NoEncryption(),
    ).decode()

    certificate_pem = cert.public_bytes(serialization.Encoding.PEM).decode()

    ca_cert_pem = ca_cert.public_bytes(serialization.Encoding.PEM).decode()

    logger.info('Issued MQTT certificate for Scout %s (CN=%s)', serial_number, cn)

    return {
        'cn': cn,
        'certificate_pem': certificate_pem,
        'private_key_pem': private_key_pem,
        'ca_cert_pem': ca_cert_pem,
    }
