# Generated by Django 4.2.30 on 2026-05-29 06:00

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('feeds', '0001_initial'),
        ('readings', '0006_stream_billing_role'),
        ('accounts', '0007_tenant_gst_rate_tenant_invoice_number_format_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('customer_reference', models.CharField(blank=True, default='', help_text='External reference (e.g. tenancy code, lot number). Unique per tenant when set.', max_length=100)),
                ('contact_email', models.EmailField(blank=True, default='', max_length=254)),
                ('contact_phone', models.CharField(blank=True, default='', max_length=50)),
                ('billing_address', models.JSONField(blank=True, default=dict, help_text='Postal address as a dict: {street, suburb, state, postcode, country}. Stored flexibly so international addresses can be added without migrations.')),
                ('abn', models.CharField(blank=True, default='', help_text='Australian Business Number (11 digits, optionally with spaces).', max_length=14)),
                ('account_type', models.CharField(choices=[('ppa_host', 'PPA host (solar host customer)'), ('en_tenant', 'Embedded-network tenant'), ('internal', 'Internal (e.g. common-area services)')], default='ppa_host', max_length=20)),
                ('invoice_email_recipients', django.contrib.postgres.fields.ArrayField(base_field=models.EmailField(max_length=254), blank=True, default=list, help_text='Email addresses that receive the invoice PDF on finalize.', size=None)),
                ('floor_area_sqm', models.DecimalField(blank=True, decimal_places=2, help_text='Net lettable area (NLA). Used by `by_floor_area` apportionment.', max_digits=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('activated_at', models.DateTimeField(blank=True, help_text='When the account first started consuming billable energy. Drives mid-cycle pro-rata.', null=True)),
                ('deactivated_at', models.DateTimeField(blank=True, help_text='Move-out date. Drives a pro-rata final invoice in Sprint 31.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent_account', models.ForeignKey(blank=True, help_text='Informational grouping only (e.g. site → tenancies).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_accounts', to='billing.billingaccount')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing_accounts', to='accounts.tenant')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BillingAccountTariffAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dimension_filter', models.JSONField(blank=True, default=dict, help_text='Subset of the dataset rows that apply to this account, e.g. {"plan_code": "stage1-2026"}. Empty means all rows in the dataset.')),
                ('version', models.CharField(blank=True, help_text='Pinned version (e.g. "2025-26"). Null follows the latest active.', max_length=50, null=True)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('billing_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tariff_assignments', to='billing.billingaccount')),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='billing_account_assignments', to='feeds.referencedataset')),
                ('stream', models.ForeignKey(blank=True, help_text='Optional — null means all billing-role streams on this account.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='billing_tariff_assignments', to='readings.stream')),
            ],
            options={
                'ordering': ['-effective_from'],
            },
        ),
        migrations.CreateModel(
            name='BillingAccountMeter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, help_text='Null means the link is open-ended (no end date set).', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('billing_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meter_links', to='billing.billingaccount')),
                ('stream', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='billing_account_links', to='readings.stream')),
            ],
            options={
                'ordering': ['-effective_from'],
            },
        ),
        migrations.CreateModel(
            name='BillingAccountAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('deactivated', 'Deactivated')], max_length=20)),
                ('changed_fields', models.JSONField(default=dict, help_text='Per-field before/after diff. See model docstring.')),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
                ('actor_user', models.ForeignKey(blank=True, help_text='User who triggered the action. Null only for system-initiated changes.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billing_account_audit_entries', to=settings.AUTH_USER_MODEL)),
                ('billing_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_log_entries', to='billing.billingaccount')),
            ],
            options={
                'ordering': ['-occurred_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='billingaccount',
            constraint=models.UniqueConstraint(condition=models.Q(('customer_reference', ''), _negated=True), fields=('tenant', 'customer_reference'), name='billing_account_unique_customer_ref_per_tenant'),
        ),
    ]
