# Generated by Django 4.2.30 on 2026-06-01 04:21

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('readings', '0006_stream_billing_role'),
        ('devices', '0010_site_common_area_apportionment_method_and_more'),
        ('accounts', '0007_tenant_gst_rate_tenant_invoice_number_format_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billing_account_ids', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=list, help_text='Explicit account filter within the site. Empty means "every active billing account on this site within the run period".', size=None)),
                ('period_start', models.DateTimeField(help_text='Run window start, UTC (inclusive).')),
                ('period_end', models.DateTimeField(help_text='Run window end, UTC (exclusive).')),
                ('timezone_snapshot', models.CharField(help_text='Snapshot of tenant.timezone at run create time (IANA).', max_length=64)),
                ('aggregate_period', models.CharField(choices=[('5min', '5 minutes'), ('30min', '30 minutes'), ('1h', '1 hour')], default='30min', help_text='IntervalAggregate period the engine walks. 30m by default.', max_length=8)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('computing', 'Computing'), ('review', 'Review'), ('draft', 'Draft'), ('finalized', 'Finalized'), ('voided', 'Voided'), ('failed', 'Failed')], default='queued', max_length=20)),
                ('failed_step', models.CharField(blank=True, choices=[('resolve_scope', 'Resolve scope'), ('snapshot', 'Snapshot'), ('compute_line_items', 'Compute line items'), ('mark_draft', 'Mark draft')], help_text='Which step threw on the last attempt. Used by retry.', max_length=30, null=True)),
                ('failure_detail', models.TextField(blank=True, default='', help_text='Exception summary populated on failure.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('computed_at', models.DateTimeField(blank=True, null=True)),
                ('finalized_at', models.DateTimeField(blank=True, null=True)),
                ('voided_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billing_runs_created', to=settings.AUTH_USER_MODEL)),
                ('finalized_by', models.ForeignKey(blank=True, help_text='Set when Sprint 32 finalize runs.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billing_runs_finalized', to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(help_text='Required in v1. Cross-site / portfolio runs deferred (v1.1).', on_delete=django.db.models.deletion.PROTECT, related_name='billing_runs', to='devices.site')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing_runs', to='accounts.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BillingSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('billing_account_ids', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=list, help_text='Explicit account filter. Empty means every active account on the site.', size=None)),
                ('aggregate_period', models.CharField(choices=[('5min', '5 minutes'), ('30min', '30 minutes'), ('1h', '1 hour')], default='30min', max_length=8)),
                ('cadence', models.CharField(choices=[('monthly_calendar', 'Monthly (calendar)'), ('monthly_anchor', 'Monthly (anchor day)'), ('quarterly', 'Quarterly'), ('custom_cron', 'Custom cron')], max_length=30)),
                ('anchor_day', models.PositiveSmallIntegerField(blank=True, help_text='Day of month for monthly_anchor cadence (1–31).', null=True)),
                ('period_offset_days', models.SmallIntegerField(default=0, help_text='Days to wait after the period ends before dispatching, so last-day data has time to land.')),
                ('custom_cron', models.CharField(blank=True, default='', help_text='Standard 5-field cron string when cadence=custom_cron.', max_length=120)),
                ('auto_finalize', models.BooleanField(default=False, help_text='Sprint 32 hook: finalize the run automatically when computed.')),
                ('is_active', models.BooleanField(default=True)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('next_run_at', models.DateTimeField(blank=True, help_text='Next time the beat dispatcher will fire this schedule.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='billing_schedules', to='devices.site')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing_schedules', to='accounts.tenant')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BillingLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_kind', models.CharField(choices=[('energy', 'Energy'), ('supply', 'Supply charge'), ('discount', 'Discount'), ('adjustment', 'Adjustment'), ('credit', 'Credit (feed-in)'), ('common_area_share', 'Common-area share (B3)')], max_length=30)),
                ('period_name', models.CharField(blank=True, default='', help_text='TOU period name from the tariff (peak/off_peak/flat). Blank for non-energy lines.', max_length=50)),
                ('kwh', models.DecimalField(blank=True, decimal_places=6, help_text='Null on non-energy lines (supply, adjustment).', max_digits=18, null=True)),
                ('rate_cents_per_kwh', models.DecimalField(blank=True, decimal_places=6, help_text='Energy rate applied. Null on non-energy lines.', max_digits=12, null=True)),
                ('amount_cents', models.IntegerField(help_text='Line amount in cents (signed; negative for credits).')),
                ('gst_cents', models.IntegerField(default=0, help_text='GST on this line in cents. amount_cents * tenant.gst_rate, rounded.')),
                ('quality_summary', models.JSONField(blank=True, default=dict, help_text='Roll-up of source IntervalAggregate quality_breakdown for this line.')),
                ('billing_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='billing_line_items', to='billing.billingaccount')),
                ('billing_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='billing.billingrun')),
                ('source_account', models.ForeignKey(blank=True, help_text='Set on common_area_share lines (B3) to link back to the internal account.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='billing.billingaccount')),
                ('stream', models.ForeignKey(blank=True, help_text='Null for supply / adjustment lines not tied to a single stream.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='billing_line_items', to='readings.stream')),
            ],
            options={
                'ordering': ['billing_account_id', 'line_kind', 'period_name'],
            },
        ),
        migrations.CreateModel(
            name='BillingRunSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interval_aggregate_ids', django.contrib.postgres.fields.ArrayField(base_field=models.BigIntegerField(), default=list, help_text='IntervalAggregate IDs that contributed to this stream’s total.', size=None)),
                ('computed_kwh', models.DecimalField(decimal_places=6, default=0, help_text='Sum of measured kWh across the snapshot intervals.', max_digits=18)),
                ('quality_summary', models.JSONField(blank=True, default=dict, help_text='Aggregate counts of source quality flags. Shape: {measured, estimated, substituted, gap}.')),
                ('billing_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='billing_run_snapshots', to='billing.billingaccount')),
                ('billing_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='billing.billingrun')),
                ('stream', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='billing_run_snapshots', to='readings.stream')),
            ],
            options={
                'indexes': [models.Index(fields=['billing_run', 'billing_account'], name='billing_bil_billing_2482ce_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='billingrunsnapshot',
            constraint=models.UniqueConstraint(fields=('billing_run', 'billing_account', 'stream'), name='billing_snapshot_unique_per_run_account_stream'),
        ),
        migrations.AddIndex(
            model_name='billingrun',
            index=models.Index(fields=['tenant', '-created_at'], name='billing_bil_tenant__0c893c_idx'),
        ),
        migrations.AddIndex(
            model_name='billingrun',
            index=models.Index(fields=['site', 'period_start', 'period_end'], name='billing_bil_site_id_c221c3_idx'),
        ),
        migrations.AddIndex(
            model_name='billinglineitem',
            index=models.Index(fields=['billing_run', 'billing_account'], name='billing_bil_billing_104223_idx'),
        ),
    ]
