# Generated by Django 4.2.30 on 2026-06-28 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_sprint32_invoices'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolarAllocationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interval_start', models.DateTimeField(help_text='UTC start of the interval this allocation covers (aligned to the run aggregate_period).')),
                ('allocated_kwh', models.DecimalField(decimal_places=6, help_text='Solar kWh allocated to this child for this interval.', max_digits=18)),
                ('pool_kwh', models.DecimalField(decimal_places=6, help_text='The allocatable solar pool for this interval (max(0, Σ generation − gate_export), clamped to total child import). Σ allocated_kwh across children equals this value exactly.', max_digits=18)),
                ('child_grid_import_kwh', models.DecimalField(decimal_places=6, help_text="This child's grid_import for the interval — the pro-rata weight.", max_digits=18)),
                ('allocation_method', models.CharField(choices=[('pro_rata_consumption', 'Pro-rata by consumption'), ('equal_share', 'Equal share'), ('fixed_proportion', 'Fixed proportion')], default='pro_rata_consumption', max_length=30)),
            ],
            options={
                'ordering': ['interval_start', 'billing_account_id'],
            },
        ),
        migrations.RenameIndex(
            model_name='billinginvoice',
            new_name='billing_bil_billing_9fd6fc_idx',
            old_name='billing_inv_billing_idx',
        ),
        migrations.AddField(
            model_name='billingaccounttariffassignment',
            name='applies_to_role',
            field=models.CharField(blank=True, default='', help_text='Sprint 33: which billing leg this tariff prices. Mirrors readings.Stream.BillingRole values — e.g. "consumption_from_solar" for the solar-allocated leg of an embedded-network tenant invoice, "consumption" for the remaining grid leg. Blank means the assignment applies regardless of leg (the single-rate PPA path).', max_length=30),
        ),
        migrations.AlterField(
            model_name='billingrun',
            name='failed_step',
            field=models.CharField(blank=True, choices=[('resolve_scope', 'Resolve scope'), ('snapshot', 'Snapshot'), ('allocate_solar', 'Allocate solar (hierarchical)'), ('compute_line_items', 'Compute line items'), ('mark_draft', 'Mark draft')], help_text='Which step threw on the last attempt. Used by retry.', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='solarallocationrecord',
            name='billing_account',
            field=models.ForeignKey(help_text='The child (embedded-network tenant) account receiving the allocation.', on_delete=django.db.models.deletion.PROTECT, related_name='solar_allocations', to='billing.billingaccount'),
        ),
        migrations.AddField(
            model_name='solarallocationrecord',
            name='billing_run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solar_allocations', to='billing.billingrun'),
        ),
        migrations.AddIndex(
            model_name='solarallocationrecord',
            index=models.Index(fields=['billing_run', 'billing_account'], name='billing_sol_billing_15398b_idx'),
        ),
        migrations.AddConstraint(
            model_name='solarallocationrecord',
            constraint=models.UniqueConstraint(fields=('billing_run', 'billing_account', 'interval_start'), name='solar_allocation_unique_per_run_account_interval'),
        ),
    ]
