# Generated by Django 4.2.30 on 2026-07-07 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0010_site_common_area_apportionment_method_and_more'),
        ('billing', '0004_sprint33_solar_allocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingrun',
            name='notes',
            field=models.TextField(blank=True, default='', help_text='Free-text operator notes. Sprint 34: records the mandatory justification when a run over reconciliation tolerance is force-finalized.'),
        ),
        migrations.AlterField(
            model_name='billingrun',
            name='failed_step',
            field=models.CharField(blank=True, choices=[('resolve_scope', 'Resolve scope'), ('snapshot', 'Snapshot'), ('allocate_solar', 'Allocate solar (hierarchical)'), ('compute_line_items', 'Compute line items'), ('reconcile', 'Reconcile (hierarchical)'), ('mark_draft', 'Mark draft')], help_text='Which step threw on the last attempt. Used by retry.', max_length=30, null=True),
        ),
        migrations.CreateModel(
            name='ReconciliationReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gate_import_kwh', models.DecimalField(decimal_places=6, default=0, max_digits=18)),
                ('generation_kwh', models.DecimalField(decimal_places=6, default=0, max_digits=18)),
                ('gate_export_kwh', models.DecimalField(decimal_places=6, default=0, max_digits=18)),
                ('child_grid_import_total_kwh', models.DecimalField(decimal_places=6, default=0, max_digits=18)),
                ('common_area_total_kwh', models.DecimalField(decimal_places=6, default=0, max_digits=18)),
                ('computed_losses_kwh', models.DecimalField(decimal_places=6, default=0, help_text='input − output; the unaccounted residual (may be negative).', max_digits=18)),
                ('variance_percent', models.DecimalField(decimal_places=4, default=0, help_text='|losses| / input × 100.', max_digits=9)),
                ('within_tolerance', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('ok', 'Within tolerance'), ('exceeded', 'Variance exceeded')], default='ok', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('billing_run', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reconciliation_report', to='billing.billingrun')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reconciliation_reports', to='devices.site')),
            ],
        ),
    ]
