# Generated by Django 4.2.29 on 2026-03-17 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_notificationgroup_notificationgroupmember'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='battery_critical_threshold',
            field=models.IntegerField(default=20, help_text='Battery level (%) below which activity level becomes critical.'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='battery_degraded_threshold',
            field=models.IntegerField(default=40, help_text='Battery level (%) below which activity level becomes degraded.'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='offline_approaching_percent',
            field=models.IntegerField(default=75, help_text='Percentage of the offline threshold elapsed that triggers degraded activity level. e.g. 75 means "degraded when 75%% of the threshold time has passed without a message".'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='signal_critical_threshold',
            field=models.IntegerField(default=-85, help_text='Signal strength (dBm) below which activity level becomes critical.'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='signal_degraded_threshold',
            field=models.IntegerField(default=-70, help_text='Signal strength (dBm) below which activity level becomes degraded.'),
        ),
    ]
