# Generated by Django 4.2.30 on 2026-05-29 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_tenantinvite'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='gst_rate',
            field=models.DecimalField(decimal_places=4, default='0.1000', help_text='GST rate applied at invoice total (default 0.10 = 10%).', max_digits=5),
        ),
        migrations.AddField(
            model_name='tenant',
            name='invoice_number_format',
            field=models.CharField(default='INV-{YYYY}-{seq:06d}', help_text='Format string for invoice numbers. Supported tokens: {YYYY} (year), {seq:06d} (zero-padded sequence). Sequence increments atomically per tenant.', max_length=120),
        ),
        migrations.AddField(
            model_name='tenant',
            name='invoice_number_sequence',
            field=models.PositiveIntegerField(default=0, help_text='Atomic per-tenant counter — incremented under SELECT FOR UPDATE.'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='invoice_pdf_template_id',
            field=models.PositiveIntegerField(blank=True, help_text='Reserved for a stored HTML/CSS invoice template (Sprint 32 will wire the FK target). Nullable means the platform default applies.', null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='invoice_settlement_disclaimer',
            field=models.TextField(blank=True, help_text='Editable boilerplate rendered on en_tenant invoices to keep the invoice-grade-not-settlement-grade boundary visible to end customers. Null falls back to the platform default.', null=True),
        ),
    ]
