# Generated by Django 4.2.29 on 2026-03-16 21:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_notificationgroup_notificationgroupmember'),
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('connection_type', models.CharField(choices=[('mqtt', 'MQTT (push)'), ('api', '3rd Party API (poll)')], default='mqtt', max_length=20)),
                ('is_push', models.BooleanField(default=True, help_text='True if the device pushes data (MQTT). False if the platform polls (API).')),
                ('default_offline_threshold_minutes', models.PositiveIntegerField(default=10, help_text='Minutes of silence before a device of this type is marked offline.')),
                ('command_ack_timeout_seconds', models.PositiveIntegerField(default=30, help_text='Seconds to wait for a command acknowledgment before marking timed_out.')),
                ('commands', models.JSONField(blank=True, default=list, help_text='Array of command definitions. Each entry: {name, label, description, params: [{name, label, type}]}')),
                ('stream_type_definitions', models.JSONField(blank=True, default=list, help_text='Hint array used during stream auto-discovery. Each entry: {key, label, data_type, unit}')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('serial_number', models.CharField(help_text='Hardware serial number — must be unique across all tenants.', max_length=255, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('rejected', 'Rejected'), ('deactivated', 'Deactivated')], default='pending', max_length=20)),
                ('offline_threshold_override_minutes', models.PositiveIntegerField(blank=True, help_text='If set, overrides the device type default offline threshold for this device.', null=True)),
                ('topic_format', models.CharField(blank=True, choices=[('legacy_v1', 'Legacy v1'), ('fieldmouse_v2', 'Fieldmouse v2')], help_text='Auto-detected from incoming MQTT traffic. Null until first message received.', max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='devices', to='devices.devicetype')),
                ('gateway_device', models.ForeignKey(blank=True, help_text='Parent Scout that bridges this device over MQTT, if applicable.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bridged_devices', to='devices.device')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='devices.site')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='accounts.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
