# Generated by Django 4.2.29 on 2026-03-17 04:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_devicetype_device'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceHealth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_online', models.BooleanField(default=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('first_active_at', models.DateTimeField(blank=True, null=True)),
                ('signal_strength', models.IntegerField(blank=True, help_text='Signal strength in dBm. Null for legacy v1 devices.', null=True)),
                ('battery_level', models.IntegerField(blank=True, help_text='Battery level as a percentage (0–100). Null for legacy v1 devices.', null=True)),
                ('activity_level', models.CharField(choices=[('normal', 'Normal'), ('degraded', 'Degraded'), ('critical', 'Critical')], default='normal', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='devicehealth', to='devices.device')),
            ],
        ),
    ]
