# Generated by Django 4.2.30 on 2026-05-27 21:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import encrypted_model_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0003_rulecondition_channel_rulecondition_dataset_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('devices', '0008_commandlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='is_virtual',
            field=models.BooleanField(default=False, help_text='True for platform-created virtual devices (e.g. the per-site `site_composite` host of cross-device derived streams). Virtual devices have no MQTT credentials and do not ingest telemetry.'),
        ),
        migrations.AlterField(
            model_name='commandlog',
            name='sent_by',
            field=models.ForeignKey(blank=True, help_text='User who sent the command. Null if triggered by a rule.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_commands', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='commandlog',
            name='triggered_by_rule',
            field=models.ForeignKey(blank=True, help_text='Rule that triggered this command. Null if sent manually.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triggered_commands', to='rules.rule'),
        ),
        migrations.AlterField(
            model_name='device',
            name='mqtt_certificate',
            field=models.TextField(blank=True, help_text='PEM-encoded client certificate (certificate mode only). Public — safe to store unencrypted. Provide to the device operator alongside the private key for Scout firmware configuration.', null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='mqtt_password',
            field=encrypted_model_fields.fields.EncryptedTextField(blank=True, help_text='Encrypted MQTT password (password mode only). Provide to the device operator for Scout firmware configuration.', null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='mqtt_private_key',
            field=encrypted_model_fields.fields.EncryptedTextField(blank=True, help_text='Encrypted PEM-encoded private key (certificate mode only). Provide to the device operator for Scout firmware configuration. Clear this field once the operator confirms the key has been loaded.', null=True),
        ),
    ]
