# Generated by Django 4.2.30 on 2026-05-29 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0009_device_is_virtual_alter_commandlog_sent_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='common_area_apportionment_method',
            field=models.CharField(choices=[('pro_rata_consumption', 'Pro-rata by tenant consumption'), ('equal_share', 'Equal share per tenant'), ('by_floor_area', 'By tenant floor area (NLA)')], default='pro_rata_consumption', help_text='How common-area energy is split across tenant accounts at billing time.', max_length=32),
        ),
        migrations.AddField(
            model_name='site',
            name='embedded_network_exemption_id',
            field=models.CharField(blank=True, default='', help_text='AER embedded-network registration / exemption reference (free text).', max_length=64),
        ),
        migrations.AddField(
            model_name='site',
            name='is_hierarchical',
            field=models.BooleanField(default=False, help_text='True when this site is an embedded network — has a gate meter parent and child meters that bill end customers separately.'),
        ),
        migrations.AddField(
            model_name='site',
            name='reconciliation_tolerance_percent',
            field=models.DecimalField(decimal_places=2, default=1.5, help_text='Percent variance between gate-meter energy and the sum of child + common-area meters before a billing run is flagged for review.', max_digits=5),
        ),
    ]
