# Generated by Django 4.2.29 on 2026-03-17 03:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices', '0002_devicetype_device'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='Machine-readable stream key as reported by the device.', max_length=255)),
                ('label', models.CharField(blank=True, help_text='Human-readable label — editable by Tenant Admin.', max_length=255)),
                ('unit', models.CharField(blank=True, help_text='Unit of measurement, e.g. "°C", "%", "L/min".', max_length=50)),
                ('data_type', models.CharField(choices=[('numeric', 'Numeric'), ('boolean', 'Boolean'), ('string', 'String')], default='numeric', max_length=20)),
                ('display_enabled', models.BooleanField(default=True, help_text='Controls dashboard visibility. Data is always stored regardless of this flag.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='streams', to='devices.device')),
            ],
            options={
                'ordering': ['key'],
                'unique_together': {('device', 'key')},
            },
        ),
        migrations.CreateModel(
            name='StreamReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.JSONField(help_text='Stored as JSON to support numeric, boolean, and string values.')),
                ('timestamp', models.DateTimeField(help_text='Time the reading was ingested by the server.')),
                ('ingested_at', models.DateTimeField(auto_now_add=True)),
                ('stream', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='readings.stream')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['stream', '-timestamp'], name='readings_st_stream__28fa6f_idx')],
            },
        ),
        migrations.CreateModel(
            name='RuleStreamIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_id', models.PositiveIntegerField(db_index=True)),
                ('stream', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rule_index_entries', to='readings.stream')),
            ],
            options={
                'unique_together': {('stream', 'rule_id')},
            },
        ),
    ]
