# Generated by Django 4.2.30 on 2026-05-27 21:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('readings', '0003_dataexport'),
    ]

    operations = [
        migrations.AddField(
            model_name='stream',
            name='stream_type',
            field=models.CharField(choices=[('raw', 'Raw (ingested)'), ('derived', 'Derived (computed)')], default='raw', help_text='Raw = ingested from a device. Derived = computed from other streams.', max_length=20),
        ),
        migrations.CreateModel(
            name='DerivedStream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formula', models.CharField(choices=[('delta', 'Δ (current − previous)'), ('sum', 'Σ sources at same minute'), ('difference', 'A − B at same minute'), ('scale', 'source × factor'), ('window_min', 'rolling min over N minutes'), ('window_max', 'rolling max over N minutes')], max_length=20)),
                ('params', models.JSONField(blank=True, default=dict, help_text='Formula-specific params. delta: max_gap_minutes (optional int). scale: factor (float). window_min/window_max: window_minutes (int). difference: source_a_id / source_b_id (override ordering).')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_streams', models.ManyToManyField(help_text='One or more source streams. delta/scale/window_min/window_max take 1; sum takes 1+ (cross-device allowed); difference takes exactly 2 (A, B).', related_name='consumer_derived_streams', to='readings.stream')),
                ('stream', models.OneToOneField(help_text='The virtual output Stream this config writes into. Must have stream_type=derived.', on_delete=django.db.models.deletion.CASCADE, related_name='derived_config', to='readings.stream')),
            ],
        ),
        migrations.CreateModel(
            name='DerivedStreamSourceIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('derived_stream', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_index_entries', to='readings.derivedstream')),
                ('source_stream', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='derived_index_entries', to='readings.stream')),
            ],
            options={
                'unique_together': {('source_stream', 'derived_stream')},
            },
        ),
    ]
