# Generated by Django 4.2.30 on 2026-05-28 05:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('readings', '0004_stream_stream_type_derivedstream_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stream',
            name='aggregation_kind_default',
            field=models.CharField(choices=[('sum', 'Sum (energy)'), ('mean', 'Mean (instantaneous)'), ('min', 'Minimum'), ('max', 'Maximum'), ('last', 'Last (cumulative)')], default='mean', help_text='The aggregation kind maintained by the IntervalAggregate beat task. Use sum for energy streams, mean for instantaneous (power/voltage/current), last for cumulative counters. Extra kinds can be computed on demand via the backfill endpoint.', max_length=10),
        ),
        migrations.AddField(
            model_name='streamreading',
            name='quality',
            field=models.CharField(choices=[('measured', 'Measured (raw)'), ('estimated', 'Estimated'), ('substituted', 'Substituted'), ('gap', 'Gap (no data)')], default='measured', help_text='Data quality flag (Sprint 28). Raw readings = measured. Derived streams inherit the worst-quality input. v1 does not estimate gaps.', max_length=20),
        ),
        migrations.CreateModel(
            name='IntervalAggregate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(choices=[('5min', '5 minutes'), ('30min', '30 minutes'), ('1h', '1 hour'), ('1d', '1 day'), ('1mo', '1 month')], max_length=10)),
                ('period_start', models.DateTimeField(help_text='UTC-aligned bucket boundary (e.g. 2026-05-28T00:05:00Z for a 5-min bucket).')),
                ('aggregation_kind', models.CharField(choices=[('sum', 'Sum (energy)'), ('mean', 'Mean (instantaneous)'), ('min', 'Minimum'), ('max', 'Maximum'), ('last', 'Last (cumulative)')], max_length=10)),
                ('value', models.JSONField(blank=True, help_text='Aggregated value. Null for gap periods (count=0).', null=True)),
                ('count', models.PositiveIntegerField(default=0, help_text='Number of source readings included in this aggregate.')),
                ('quality', models.CharField(choices=[('measured', 'Measured (raw)'), ('estimated', 'Estimated'), ('substituted', 'Substituted'), ('gap', 'Gap (no data)')], default='measured', help_text='Derived aggregate quality via worst-input rule.', max_length=20)),
                ('quality_breakdown', models.JSONField(blank=True, default=dict, help_text='Map of quality → count for the source readings, e.g. {"measured": 4, "estimated": 1}. Empty {} for gap periods.')),
                ('computed_at', models.DateTimeField(auto_now=True)),
                ('stream', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aggregates', to='readings.stream')),
            ],
            options={
                'ordering': ['-period_start'],
                'indexes': [models.Index(fields=['stream', '-period_start'], name='readings_in_stream__658c7a_idx')],
                'unique_together': {('stream', 'period', 'period_start', 'aggregation_kind')},
            },
        ),
    ]
