# Generated by Django 4.2.30 on 2026-05-29 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readings', '0005_stream_aggregation_kind_default_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stream',
            name='billing_role',
            field=models.CharField(blank=True, choices=[('grid_import', 'Grid import (kWh consumed from grid)'), ('grid_export', 'Grid export (kWh exported to grid)'), ('generation', 'Generation (solar kWh)'), ('bess_charge', 'BESS charge (kWh into battery)'), ('bess_discharge', 'BESS discharge (kWh out of battery)'), ('consumption', 'Consumption (total kWh)'), ('consumption_from_solar', 'Consumption from solar (kWh)'), ('net', 'Net (signed kWh)')], help_text='Sprint 29: When set, marks this stream as a billable quantity for the billing engine. Streams without a billing_role are unaffected by billing runs.', max_length=32, null=True),
        ),
    ]
