# Generated by Django 4.2.29 on 2026-03-18 03:20

import apps.integrations.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0003_devicehealth'),
        ('integrations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='thirdpartyapiprovider',
            name='refresh_url',
            field=models.URLField(blank=True, default='', help_text='Separate refresh endpoint, if different from token_url (e.g. SoilScout uses /auth/token/refresh/). Leave blank to reuse token_url for refresh.', max_length=500),
        ),
        migrations.AddField(
            model_name='thirdpartyapiprovider',
            name='token_url',
            field=models.URLField(blank=True, default='', help_text='Token endpoint for OAuth2 auth types. Leave blank for non-OAuth2 providers.', max_length=500),
        ),
        migrations.AlterField(
            model_name='datasource',
            name='auth_token_cache',
            field=apps.integrations.fields.EncryptedJSONField(blank=True, default=dict, help_text='Encrypted token cache for oauth2 auth types (access/refresh tokens + expiry).'),
        ),
        migrations.AlterField(
            model_name='datasource',
            name='credentials',
            field=apps.integrations.fields.EncryptedJSONField(default=dict, help_text='Encrypted tenant credentials — filled from provider auth_param_schema.'),
        ),
        migrations.AlterField(
            model_name='datasourcedevice',
            name='active_stream_keys',
            field=models.JSONField(default=list, help_text='Subset of provider available_streams keys the tenant has activated.'),
        ),
        migrations.AlterField(
            model_name='datasourcedevice',
            name='consecutive_poll_failures',
            field=models.PositiveIntegerField(default=0, help_text='Consecutive poll failures. Reset to 0 on success.'),
        ),
        migrations.AlterField(
            model_name='datasourcedevice',
            name='external_device_id',
            field=models.CharField(help_text='Device ID as returned by the provider discovery endpoint.', max_length=500),
        ),
        migrations.AlterField(
            model_name='datasourcedevice',
            name='external_device_name',
            field=models.CharField(blank=True, help_text='Device name as returned by the provider discovery endpoint.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='datasourcedevice',
            name='is_active',
            field=models.BooleanField(default=True, help_text='False = deactivated. Polling stops but history is retained.'),
        ),
        migrations.AlterField(
            model_name='datasourcedevice',
            name='virtual_device',
            field=models.OneToOneField(help_text='The virtual Device record representing this external device.', on_delete=django.db.models.deletion.CASCADE, related_name='datasource_device', to='devices.device'),
        ),
        migrations.AlterField(
            model_name='thirdpartyapiprovider',
            name='auth_param_schema',
            field=models.JSONField(default=list, help_text='Array of credential field definitions. Each entry: {key, label, type (text/password), required (bool)}. Used to auto-generate the credential entry form for tenants.'),
        ),
        migrations.AlterField(
            model_name='thirdpartyapiprovider',
            name='available_streams',
            field=models.JSONField(default=list, help_text='Array of stream definitions. Each entry: {key, label, unit, data_type, jsonpath}.'),
        ),
        migrations.AlterField(
            model_name='thirdpartyapiprovider',
            name='default_poll_interval_seconds',
            field=models.PositiveIntegerField(default=300, help_text='How often to poll each connected device (seconds). Default: 5 minutes.'),
        ),
        migrations.AlterField(
            model_name='thirdpartyapiprovider',
            name='detail_endpoint',
            field=models.JSONField(default=dict, help_text='Detail endpoint config: {path_template (with {device_id}), method}. Called per device to retrieve current readings.'),
        ),
        migrations.AlterField(
            model_name='thirdpartyapiprovider',
            name='discovery_endpoint',
            field=models.JSONField(default=dict, help_text='Discovery endpoint config: {path, method, device_id_jsonpath, device_name_jsonpath (optional)}.'),
        ),
    ]
