# Generated by Django 4.2.29 on 2026-03-24 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0004_provider_max_requests_per_second'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thirdpartyapiprovider',
            name='auth_type',
            field=models.CharField(choices=[('api_key_header', 'API Key (Header)'), ('api_key_query', 'API Key (Query Parameter)'), ('bearer_token', 'Bearer Token'), ('basic_auth', 'Basic Auth (Username/Password)'), ('oauth2_client_credentials', 'OAuth2 Client Credentials'), ('oauth2_password', 'OAuth2 Password Grant'), ('dual_api_key', 'Dual API Key (Key as query param + Secret as header)')], max_length=40),
        ),
    ]
