# Generated by Django 4.2.29 on 2026-03-24 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0005_add_dual_api_key_auth_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='thirdpartyapiprovider',
            name='device_detail_endpoint',
            field=models.JSONField(blank=True, default=dict, help_text='Optional device metadata endpoint. Called as a background task after devices are connected to populate virtual device names from the provider. Schema: {path_template (with {device_id}), method, name_jsonpath}. Leave empty for providers where discovery already returns names (e.g. SoilScout, Davis).'),
        ),
        migrations.AlterField(
            model_name='thirdpartyapiprovider',
            name='detail_endpoint',
            field=models.JSONField(default=dict, help_text='Measurement endpoint config: {path_template (with {device_id}), method, params (optional dict of query params — values may contain time tokens: {from_unix}, {to_unix} for Unix timestamps; {from_iso}, {to_iso} for ISO 8601 UTC strings e.g. 2025-04-15T09:00:00Z), window_seconds (int — time window for first poll when last_polled_at is None, default 300)}. Called per device on every poll cycle to retrieve current readings.'),
        ),
    ]
