# Generated by Django 4.2.30 on 2026-06-01 01:14

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('integrations', '0007_add_per_device_poll_interval'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasourcedevice',
            name='is_backfilling',
            field=models.BooleanField(default=False, help_text='True while a DataSourceBackfillJob owns this device (Sprint 29a). The beat task skips devices with this flag set so live polling and backfill cannot run concurrently against the same provider endpoint for one device. A janitor task reconciles orphaned flags against DataSourceBackfillJob.status after a worker crash.'),
        ),
        migrations.AddField(
            model_name='thirdpartyapiprovider',
            name='history_chunk_days',
            field=models.PositiveSmallIntegerField(default=7, help_text='Day-window size the backfill task uses when splitting a request into successive history endpoint calls (Sprint 29a). Default 7.', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='thirdpartyapiprovider',
            name='history_endpoint',
            field=models.JSONField(blank=True, default=dict, help_text='Optional history endpoint config (Sprint 29a). Schema: {path_template (with {device_id}), method (default GET), params (optional dict — values may contain {from_iso}/{to_iso}/{from_unix}/{to_unix} tokens, interpolated per chunk), response_root_jsonpath (default "$[*]" — iterates rows), timestamp_jsonpath (per-row, ISO 8601 or unix int)}. Per-row value extraction reuses available_streams[*].jsonpath evaluated relative to each iterated row.'),
        ),
        migrations.AddField(
            model_name='thirdpartyapiprovider',
            name='supports_history',
            field=models.BooleanField(default=False, help_text='Whether the provider exposes a history endpoint that supports tenant-driven backfill over a date range (Sprint 29a). Must be True for `history_endpoint` to be honoured.'),
        ),
        migrations.CreateModel(
            name='DataSourceBackfillJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_from', models.DateField(help_text='Backfill window start (inclusive, in tenant timezone).')),
                ('date_to', models.DateField(help_text='Backfill window end (inclusive, in tenant timezone).')),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='queued', max_length=20)),
                ('rows_fetched', models.PositiveIntegerField(default=0, help_text='Total rows iterated from provider responses across all chunks.')),
                ('rows_stored', models.PositiveIntegerField(default=0, help_text='Total new StreamReadings created (rows_fetched minus dedup hits).')),
                ('error_detail', models.TextField(blank=True, default='', help_text='Populated on failure with the exception summary.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='datasource_backfill_jobs', to=settings.AUTH_USER_MODEL)),
                ('datasource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backfill_jobs', to='integrations.datasource')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['datasource', '-created_at'], name='integration_datasou_a6ab32_idx')],
            },
        ),
    ]
