# Generated by Django 4.2.29 on 2026-04-08 18:59

import apps.integrations.fields
import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rules', '0002_alter_rule_active_days_and_more'),
        ('accounts', '0005_tenant_battery_critical_threshold_and_more'),
        ('devices', '0005_alter_devicetype_status_indicator_mappings'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='Machine-readable channel key (e.g. "rrp", "raise_reg_rrp").', max_length=100)),
                ('label', models.CharField(max_length=255)),
                ('unit', models.CharField(blank=True, default='', max_length=50)),
                ('data_type', models.CharField(choices=[('numeric', 'Numeric'), ('boolean', 'Boolean'), ('string', 'String')], default='numeric', max_length=10)),
                ('dimension_value', models.CharField(blank=True, help_text='Dimension value that identifies this channel instance (e.g. "NSW1" for a regional channel). Null for dimensionless channels.', max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['provider', 'key', 'dimension_value'],
            },
        ),
        migrations.CreateModel(
            name='FeedProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('base_url', models.URLField(max_length=500)),
                ('auth_type', models.CharField(choices=[('none', 'None (public endpoint)'), ('api_key_header', 'API Key (Header)'), ('bearer_token', 'Bearer Token'), ('oauth2_client_credentials', 'OAuth2 Client Credentials'), ('oauth2_password', 'OAuth2 Password Grant')], default='none', max_length=40)),
                ('auth_param_schema', models.JSONField(blank=True, default=list, help_text='Array of credential field definitions for scope=tenant providers. Each entry: {key, label, type (text/password), required (bool)}. Leave empty for scope=system providers with no auth.')),
                ('scope', models.CharField(choices=[('system', 'System — polled once globally, available to all tenants'), ('tenant', 'Tenant — each tenant subscribes with their own credentials')], default='system', max_length=10)),
                ('poll_interval_seconds', models.PositiveIntegerField(default=300, help_text='How often to poll (seconds). Minimum: 60s, default: 5 minutes (300s).', validators=[django.core.validators.MinValueValidator(60)])),
                ('endpoints', models.JSONField(default=list, help_text='Array of endpoint configs. Each entry: {path, method, response_root_jsonpath (optional — JSONPath to iterate rows; omit for single-object responses), dimension_key (optional — field in each row that identifies the channel variant, e.g. "REGIONID"), channels: [{key, label, unit, data_type, value_jsonpath}]}.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ReferenceDataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('dimension_schema', models.JSONField(default=list, help_text='Array defining lookup key columns. Each entry: {key, label, type}. Example: [{key: "distributor_slug", label: "Distributor", type: "string"}, {key: "tariff_code", label: "Tariff Code", type: "string"}, {key: "period_name", label: "Period", type: "string"}].')),
                ('value_schema', models.JSONField(default=list, help_text='Array defining value columns. Each entry: {key, label, type, unit}. Example: [{key: "rate_cents_per_kwh", label: "Rate", type: "decimal", unit: "c/kWh"}, {key: "daily_supply_cents", label: "Daily Supply", type: "decimal", unit: "c/day"}].')),
                ('has_time_of_use', models.BooleanField(default=False, help_text='When true, rows carry applicable_days, time_from, and time_to. The row resolver filters by current day/time in tenant timezone.')),
                ('has_version', models.BooleanField(default=False, help_text='When true, rows carry a version label (e.g. "2025-26"). Used for annually-updated datasets like network tariffs.')),
                ('scope', models.CharField(choices=[('system', 'System — managed by That Place Admin, shared across all tenants'), ('tenant', 'Tenant — each tenant manages their own rows (future use)')], default='system', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TenantFeedSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credentials', apps.integrations.fields.EncryptedJSONField(default=dict, help_text='Encrypted tenant credentials — filled from provider auth_param_schema.')),
                ('subscribed_channel_ids', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, help_text='PKs of FeedChannel records the tenant has subscribed to.', size=None)),
                ('is_active', models.BooleanField(default=True)),
                ('last_polled_at', models.DateTimeField(blank=True, null=True)),
                ('last_poll_status', models.CharField(blank=True, choices=[('ok', 'OK'), ('error', 'Error'), ('auth_failure', 'Auth Failure')], max_length=20, null=True)),
                ('last_poll_error', models.TextField(blank=True, null=True)),
                ('provider', models.ForeignKey(limit_choices_to={'scope': 'tenant'}, on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='feeds.feedprovider')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feed_subscriptions', to='accounts.tenant')),
            ],
            options={
                'ordering': ['-tenant__name'],
            },
        ),
        migrations.CreateModel(
            name='TenantDatasetAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dimension_filter', models.JSONField(help_text='Dimension values identifying the applicable rows for this site. Example: {distributor_slug: "ausgrid", tariff_code: "EA305"}. Rows whose dimensions contain all keys in this filter are candidates.')),
                ('version', models.CharField(blank=True, help_text='Pinned version label (e.g. "2025-26"). When null, the resolver always uses the latest active version.', max_length=50, null=True)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, help_text='Null = currently active. Expired assignments are retained for audit.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tenant_assignments', to='feeds.referencedataset')),
                ('site', models.ForeignKey(blank=True, help_text='Null = tenant-wide assignment. Site-specific overrides tenant-wide.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dataset_assignments', to='devices.site')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dataset_assignments', to='accounts.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReferenceDatasetRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(blank=True, help_text='Financial year or period label (e.g. "2025-26"). Required when dataset.has_version is true.', max_length=50, null=True)),
                ('dimensions', models.JSONField(help_text='Lookup key values matching dataset.dimension_schema. Example: {distributor_slug: "ausgrid", tariff_code: "EA305", period_name: "peak"}.')),
                ('values', models.JSONField(help_text='Actual data values matching dataset.value_schema. Example: {rate_cents_per_kwh: 32.50, daily_supply_cents: 110.0}.')),
                ('applicable_days', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, help_text='Days of week this row applies: 0=Mon … 6=Sun. Null = all days.', null=True, size=None)),
                ('time_from', models.TimeField(blank=True, help_text='Start of the applicable time window (wall-clock, not UTC).', null=True)),
                ('time_to', models.TimeField(blank=True, help_text='End of the applicable time window (wall-clock, not UTC).', null=True)),
                ('valid_from', models.DateField(blank=True, null=True)),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='feeds.referencedataset')),
            ],
            options={
                'ordering': ['dataset', 'version', 'id'],
            },
        ),
        migrations.CreateModel(
            name='FeedReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.JSONField(help_text='Reading value. Numeric readings stored as float; boolean as bool; string as str.')),
                ('timestamp', models.DateTimeField(db_index=True, help_text='Settlement/interval timestamp reported by the provider.')),
                ('fetched_at', models.DateTimeField(help_text='When this reading was fetched by the poller.')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='feeds.feedchannel')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='FeedChannelRuleIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rule_index_entries', to='feeds.feedchannel')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feed_channel_index_entries', to='rules.rule')),
            ],
        ),
        migrations.AddField(
            model_name='feedchannel',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channels', to='feeds.feedprovider'),
        ),
        migrations.AddConstraint(
            model_name='tenantfeedsubscription',
            constraint=models.UniqueConstraint(fields=('tenant', 'provider'), name='unique_feed_subscription_per_tenant'),
        ),
        migrations.AddConstraint(
            model_name='feedreading',
            constraint=models.UniqueConstraint(fields=('channel', 'timestamp'), name='unique_feed_reading_per_interval'),
        ),
        migrations.AddConstraint(
            model_name='feedchannelruleindex',
            constraint=models.UniqueConstraint(fields=('channel', 'rule'), name='unique_feed_channel_rule_index'),
        ),
        migrations.AddConstraint(
            model_name='feedchannel',
            constraint=models.UniqueConstraint(fields=('provider', 'key', 'dimension_value'), name='unique_feed_channel'),
        ),
    ]
