# Generated by Django 4.2.30 on 2026-05-29 04:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices', '0010_site_common_area_apportionment_method_and_more'),
        ('accounts', '0006_tenantinvite'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeterProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nmi', models.CharField(blank=True, help_text='10/11-digit National Meter Identifier — unique per tenant when set.', max_length=11, null=True)),
                ('meter_role', models.CharField(choices=[('gate', 'Gate (embedded-network parent)'), ('child', 'Child (embedded-network tenant)'), ('generation', 'Generation (solar)'), ('storage', 'Storage (BESS)'), ('consumption', 'Consumption (single-tier host)'), ('common_area', 'Common area / landlord'), ('sub_check', 'Sub-check (informational)')], max_length=20)),
                ('pattern_approval', models.CharField(blank=True, default='', help_text='e.g. "NMI-M6". Informational — surfaces on invoice footers and audit reports.', max_length=50)),
                ('phases', models.PositiveSmallIntegerField(choices=[(1, 'Single phase'), (3, 'Three phase')], default=1)),
                ('install_date', models.DateField(blank=True, null=True)),
                ('serial_number_secondary', models.CharField(blank=True, default='', help_text='Secondary serial number for bundled meter cases (e.g. CET PMC serial in a WW 6M+One installation).', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='meter_profile', to='devices.device')),
                ('parent_meter', models.ForeignKey(blank=True, help_text='For child/common_area meters at a hierarchical site: the Device that holds the gate MeterProfile. Must be on the same site.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='child_meters', to='devices.device')),
                ('tenant', models.ForeignKey(help_text='Denormalised from device.tenant — used for (tenant, nmi) uniqueness.', on_delete=django.db.models.deletion.CASCADE, related_name='meter_profiles', to='accounts.tenant')),
            ],
            options={
                'ordering': ['device__name'],
            },
        ),
        migrations.AddConstraint(
            model_name='meterprofile',
            constraint=models.UniqueConstraint(condition=models.Q(('nmi__isnull', False)), fields=('tenant', 'nmi'), name='meter_profile_unique_nmi_per_tenant'),
        ),
    ]
