# Generated by Django 4.2.29 on 2026-03-18 11:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0005_tenant_battery_critical_threshold_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('columns', models.PositiveSmallIntegerField(default=2, help_text='Number of columns in the fixed grid layout (1, 2, or 3).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created the dashboard. Nulled if the user is later deleted.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_dashboards', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboards', to='accounts.tenant')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DashboardWidget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('widget_type', models.CharField(choices=[('value_card', 'Value Card'), ('line_chart', 'Line Chart'), ('gauge', 'Gauge'), ('status_indicator', 'Status Indicator'), ('health_uptime_chart', 'Health / Uptime Chart')], default='value_card', max_length=30)),
                ('stream_ids', models.JSONField(blank=True, default=list, help_text='Array of Stream PKs this widget is bound to.')),
                ('config', models.JSONField(blank=True, default=dict, help_text='Widget-specific configuration (label override, min/max, thresholds, etc.).')),
                ('position', models.JSONField(blank=True, default=dict, help_text='Position within the dashboard grid. Format: {"order": 0}.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dashboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='widgets', to='dashboards.dashboard')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
